name: Deploiement du site HTML #nom de l'action

on: # indique où l'action sera effectuée
  push:
    branches:
      - main  # Déclenche à chaque push sur main

permissions:
  contents: read
  pages: write
  id-token: write

jobs: # précise les différentes taches de l'action
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: préparation de GitHub pages
        uses: actions/configure-pages@v3

      - name: publication automatique
        uses: actions/deploy-pages@v2
        with:
          path: ./
